import pandas as pd
from helpers.paths import PATHS
from pydantic import BaseModel


class FileReaders(BaseModel):
    """
    Class to read outputs files from XFOIL and return them as relevant data
    structures.
    """
    empty_data: bool = True

    def read_aero_file(self) -> pd.DataFrame:
        """
        Reads the aero file generated by XFOIL and returns it as a DataFrame.
        """
        aero_file_path = PATHS.outputs() / 'xfoil_output.txt'

        if not aero_file_path.exists():
            raise FileNotFoundError(f"Aero file not found at {aero_file_path}")

        # Read the file into a DataFrame

        while self.empty_data:
            df = pd.read_csv(aero_file_path, sep='\s+', skiprows=list(range(0,9)) + [11])

            if not df.empty:
                self.empty_data = False


        self.empty_data = True

        return df