import pandas as pd
from helpers.paths import PATHS
from pydantic import BaseModel
from time import sleep


class FileReaders(BaseModel):
    """
    Class to read outputs files from XFOIL and return them as relevant data
    structures.
    """
    empty_data: bool = True

    def read_aero_file(self, output_number: int) -> pd.DataFrame:
        """
        Reads the aero file generated by XFOIL and returns it as a DataFrame.
        Dynamically searches for any xfoil_output file in the outputs directory.
        """
        outputs_dir = PATHS.outputs()
        aero_file_path = None
        sleep(1)

        # Dynamically find any file starting with 'xfoil_output' in the outputs directory
        for file in outputs_dir.iterdir():
            if file.name.startswith('xfoil_output') and file.suffix == '.txt' and str(output_number-1) in file.name:
                aero_file_path = file
                break

        if not aero_file_path:
            raise FileNotFoundError(f"XFOIL output file: {file} not found in output dir")

        # Read the file into a DataFrame
        while self.empty_data:
            df = pd.read_csv(aero_file_path, sep='\\s+', skiprows=list(range(0, 9)) + [11])

            if not df.empty:
                self.empty_data = False

        self.empty_data = True

        return df